### ISSUE TITLE
name 'get_losses_pretrain' is not defined

### ISSUE THREAD

**Issue by Ruiyuan-Zhang** [absdnd/RGL_NET_Progressive_Part_Assembly#2]
Hello,

Thank you for releasing your source code.

I met a problem when trying to run your script `train.py`. The error information shows that `name 'get_losses_pretrain' is not defined`. I think it might be because you forgot to release your `loss` module.

By the way, please may I ask whether you can share your pre-trained model files for three datasets?

Thank you very much. Looking forward to your kind reply at your earliest convenience!

**Comment by absdnd** [comment]
Sorry for the delay. Thanks for pointing this out!

**Comment by Ruiyuan-Zhang** [comment]
Thanks for your replay,

when i set `models/model_Ours` to `models/model_dynamic_backup` or `model_dynamic` and using your `train.py` and `validate.py`, i faced two errors:

when train:
1. RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```shell
Traceback (most recent call last):
  File "train.py", line 463, in <module>
    fitter.fit()
  File "train.py", line 419, in fit
    self.validation()
  File "train.py", line 271, in validation
    res_total_loss, last_loss = self.forward(batch=batch, is_val=True,step=val_step, epoch = self.epoch, batch_ind=val_batch_ind, num_batch=val_num_batch, start_time=start_time, \
  File "train.py", line 159, in forward
    total_pred_part_poses = self.network(conf, input_part_pairs.float(), input_part_valids.float(), input_part_pcs.float(), instance_label, same_class_list, shape_id)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zry/experiences/RGL_NET_Progressive_Part_Assembly/models/model_dynamic_backup.py", line 454, in forward
    decoder_output = mlp_seq(input_4, decoder_input_hidden, lens)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zry/experiences/RGL_NET_Progressive_Part_Assembly/models/model_dynamic_backup.py", line 141, in forward
    decoder_output, decoder_hidden = self.forward_decoder(decoder_input.float(), decoder_hidden.float(), lens)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zry/experiences/RGL_NET_Progressive_Part_Assembly/models/model_dynamic_backup.py", line 109, in forward
    packed_seq = pack_padded_sequence(input, lengths = lens, batch_first = True, enforce_sorted = False)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 249, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```
so, I try to fix like below image.
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/71813586/164503483-94395a49-a830-4c85-8ee6-f12c7ba34505.png">

but I get a new error like below .
```shell
[W python_anomaly_mode.cpp:104] Warning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "train.py", line 462, in <module>
    fitter.fit()
  File "train.py", line 419, in fit
    self.train_one_epoch()
  File "train.py", line 362, in train_one_epoch
    res_total_loss, last_loss = self.forward(batch=batch, is_val=False, step=train_step, epoch = self.epoch, batch_ind=train_batch_ind, num_batch=train_num_batch, start_time=start_time, \
  File "train.py", line 159, in forward
    total_pred_part_poses = self.network(conf, input_part_pairs.float(), input_part_valids.float(), input_part_pcs.float(), instance_label, same_class_list, shape_id)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zry/experiences/RGL_NET_Progressive_Part_Assembly/models/model_dynamic_backup.py", line 387, in forward
    pose_feat = self.pose_extractor(cur_poses.float())
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zry/experiences/RGL_NET_Progressive_Part_Assembly/models/model_dynamic_backup.py", line 304, in forward
    x = torch.relu(self.mlp2(x))
 (function _print_stack)
Traceback (most recent call last):
  File "train.py", line 462, in <module>
    fitter.fit()
  File "train.py", line 419, in fit
    self.train_one_epoch()
  File "train.py", line 379, in train_one_epoch
    total_loss.backward()
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [13, 16, 128]], which is output 0 of ReluBackward0, is at version 62; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

when test(use `validate.py`)：
2. can not load your pre-train model file.
> First, your `validate.py` don't have `conf.hidden_size`, so I add `hidden_size=256` in `class GlobalTrainConfig`.
```shell
Traceback (most recent call last):
  File "validate.py", line 359, in <module>
    fitter.fit()
  File "validate.py", line 335, in fit
    utils.load_checkpoint_wo_optimizer(models = models, model_names = model_names, dirname = os.path.join(conf.ckpt_path), epoch = self.epoch, optimizers = optimizers, optimizer_names = optimizer_names)
  File "/home/zry/experiences/RGL_NET_Progressive_Part_Assembly/utils.py", line 349, in load_checkpoint_wo_optimizer
    model.load_state_dict(torch.load(os.path.join(dirname, filename)), strict=strict)
  File "/home/zry/miniconda/envs/RGL/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Network:
        Missing key(s) in state_dict: "mlp2.conv1.weight", "mlp2.conv1.bias", "mlp2.conv2.weight", "mlp2.conv2.bias", "mlp2.conv3.weight", "mlp2.conv3.bias", "mlp2.conv4.weight", "mlp2.conv4.bias", "mlp2.conv5.weight", "mlp2.conv5.bias", "mlp2.bn1.weight", "mlp2.bn1.bias", "mlp2.bn1.running_mean", "mlp2.bn1.running_var", "mlp2.bn2.weight", "mlp2.bn2.bias", "mlp2.bn2.running_mean", "mlp2.bn2.running_var", "mlp2.bn3.weight", "mlp2.bn3.bias", "mlp2.bn3.running_mean", "mlp2.bn3.running_var", "mlp2.bn4.weight", "mlp2.bn4.bias", "mlp2.bn4.running_mean", "mlp2.bn4.running_var", "mlp2.bn5.weight", "mlp2.bn5.bias", "mlp2.bn5.running_mean", "mlp2.bn5.running_var", "mlp2.mlp1.weight", "mlp2.mlp1.bias", "mlp2.bn6.weight", "mlp2.bn6.bias", "mlp2.bn6.running_mean", "mlp2.bn6.running_var", "mlp3_1.conv1.weight", "mlp3_1.conv1.bias", "mlp3_1.conv2.weight", "mlp3_1.conv2.bias", "mlp3_1.conv3.weight", "mlp3_1.conv3.bias", "mlp3_1.bn1.weight", "mlp3_1.bn1.bias", "mlp3_1.bn1.running_mean", "mlp3_1.bn1.running_var", "mlp3_1.bn2.weight", "mlp3_1.bn2.bias", "mlp3_1.bn2.running_mean", "mlp3_1.bn2.running_var", "mlp3_1.bn3.weight", "mlp3_1.bn3.bias", "mlp3_1.bn3.running_mean", "mlp3_1.bn3.running_var", "mlp3_2.conv1.weight", "mlp3_2.conv1.bias", "mlp3_2.conv2.weight", "mlp3_2.conv2.bias", "mlp3_2.conv3.weight", "mlp3_2.conv3.bias", "mlp3_2.bn1.weight", "mlp3_2.bn1.bias", "mlp3_2.bn1.running_mean", "mlp3_2.bn1.running_var", "mlp3_2.bn2.weight", "mlp3_2.bn2.bias", "mlp3_2.bn2.running_mean", "mlp3_2.bn2.running_var", "mlp3_2.bn3.weight", "mlp3_2.bn3.bias", "mlp3_2.bn3.running_mean", "mlp3_2.bn3.running_var", "mlp3_3.conv1.weight", "mlp3_3.conv1.bias", "mlp3_3.conv2.weight", "mlp3_3.conv2.bias", "mlp3_3.conv3.weight", "mlp3_3.conv3.bias", "mlp3_3.bn1.weight", "mlp3_3.bn1.bias", "mlp3_3.bn1.running_mean", "mlp3_3.bn1.running_var", "mlp3_3.bn2.weight", "mlp3_3.bn2.bias", "mlp3_3.bn2.running_mean", "mlp3_3.bn2.running_var", "mlp3_3.bn3.weight", "mlp3_3.bn3.bias", "mlp3_3.bn3.running_mean", "mlp3_3.bn3.running_var", "mlp4_1.conv1.weight", "mlp4_1.conv1.bias", "mlp4_1.conv2.weight", "mlp4_1.conv2.bias", "mlp4_1.conv3.weight", "mlp4_1.conv3.bias", "mlp4_1.bn1.weight", "mlp4_1.bn1.bias", "mlp4_1.bn1.running_mean", "mlp4_1.bn1.running_var", "mlp4_1.bn2.weight", "mlp4_1.bn2.bias", "mlp4_1.bn2.running_mean", "mlp4_1.bn2.running_var", "mlp4_1.bn3.weight", "mlp4_1.bn3.bias", "mlp4_1.bn3.running_mean", "mlp4_1.bn3.running_var", "mlp4_2.conv1.weight", "mlp4_2.conv1.bias", "mlp4_2.conv2.weight", "mlp4_2.conv2.bias", "mlp4_2.conv3.weight", "mlp4_2.conv3.bias", "mlp4_2.bn1.weight", "mlp4_2.bn1.bias", "mlp4_2.bn1.running_mean", "mlp4_2.bn1.running_var", "mlp4_2.bn2.weight", "mlp4_2.bn2.bias", "mlp4_2.bn2.running_mean", "mlp4_2.bn2.running_var", "mlp4_2.bn3.weight", "mlp4_2.bn3.bias", "mlp4_2.bn3.running_mean", "mlp4_2.bn3.running_var", "mlp4_3.conv1.weight", "mlp4_3.conv1.bias", "mlp4_3.conv2.weight", "mlp4_3.conv2.bias", "mlp4_3.conv3.weight", "mlp4_3.conv3.bias", "mlp4_3.bn1.weight", "mlp4_3.bn1.bias", "mlp4_3.bn1.running_mean", "mlp4_3.bn1.running_var", "mlp4_3.bn2.weight", "mlp4_3.bn2.bias", "mlp4_3.bn2.running_mean", "mlp4_3.bn2.running_var", "mlp4_3.bn3.weight", "mlp4_3.bn3.bias", "mlp4_3.bn3.running_mean", "mlp4_3.bn3.running_var", "mlp5_1.mlp.weight", "mlp5_1.mlp.bias", "mlp5_1.trans.weight", "mlp5_1.trans.bias", "mlp5_1.quat.weight", "mlp5_1.quat.bias", "mlp5_2.mlp.weight", "mlp5_2.mlp.bias", "mlp5_2.trans.weight", "mlp5_2.trans.bias", "mlp5_2.quat.weight", "mlp5_2.quat.bias", "mlp5_3.mlp.weight", "mlp5_3.mlp.bias", "mlp5_3.trans.weight", "mlp5_3.trans.bias", "mlp5_3.quat.weight", "mlp5_3.quat.bias", "relation_predictor.mlp1.weight", "relation_predictor.mlp1.bias", "relation_predictor.mlp2.weight", "relation_predictor.mlp2.bias", "relation_predictor.mlp3.weight", "relation_predictor.mlp3.bias", "relation_predictor_dense.mlp1.weight", "relation_predictor_dense.mlp1.bias", "relation_predictor_dense.mlp2.weight", "relation_predictor_dense.mlp2.bias", "relation_predictor_dense.mlp3.weight", "relation_predictor_dense.mlp3.bias", "pose_extractor.mlp1.weight", "pose_extractor.mlp1.bias", "pose_extractor.mlp2.weight", "pose_extractor.mlp2.bias", "feature_refiner.weight", "feature_refiner.bias", "seq2seqae_1.forward_decoder.gru.weight_ih_l0", "seq2seqae_1.forward_decoder.gru.weight_hh_l0", "seq2seqae_1.forward_decoder.gru.bias_ih_l0", "seq2seqae_1.forward_decoder.gru.bias_hh_l0", "seq2seqae_1.forward_decoder.gru.weight_ih_l0_reverse", "seq2seqae_1.forward_decoder.gru.weight_hh_l0_reverse", "seq2seqae_1.forward_decoder.gru.bias_ih_l0_reverse", "seq2seqae_1.forward_decoder.gru.bias_hh_l0_reverse", "seq2seqae_2.forward_decoder.gru.weight_ih_l0", "seq2seqae_2.forward_decoder.gru.weight_hh_l0", "seq2seqae_2.forward_decoder.gru.bias_ih_l0", "seq2seqae_2.forward_decoder.gru.bias_hh_l0", "seq2seqae_2.forward_decoder.gru.weight_ih_l0_reverse", "seq2seqae_2.forward_decoder.gru.weight_hh_l0_reverse", "seq2seqae_2.forward_decoder.gru.bias_ih_l0_reverse", "seq2seqae_2.forward_decoder.gru.bias_hh_l0_reverse", "seq2seqae_3.forward_decoder.gru.weight_ih_l0", "seq2seqae_3.forward_decoder.gru.weight_hh_l0", "seq2seqae_3.forward_decoder.gru.bias_ih_l0", "seq2seqae_3.forward_decoder.gru.bias_hh_l0", "seq2seqae_3.forward_decoder.gru.weight_ih_l0_reverse", "seq2seqae_3.forward_decoder.gru.weight_hh_l0_reverse", "seq2seqae_3.forward_decoder.gru.bias_ih_l0_reverse", "seq2seqae_3.forward_decoder.gru.bias_hh_l0_reverse", "seq2seqae_4.forward_decoder.gru.weight_ih_l0", "seq2seqae_4.forward_decoder.gru.weight_hh_l0", "seq2seqae_4.forward_decoder.gru.bias_ih_l0", "seq2seqae_4.forward_decoder.gru.bias_hh_l0", "seq2seqae_4.forward_decoder.gru.weight_ih_l0_reverse", "seq2seqae_4.forward_decoder.gru.weight_hh_l0_reverse", "seq2seqae_4.forward_decoder.gru.bias_ih_l0_reverse", "seq2seqae_4.forward_decoder.gru.bias_hh_l0_reverse", "seq2seqae_5.forward_decoder.gru.weight_ih_l0", "seq2seqae_5.forward_decoder.gru.weight_hh_l0", "seq2seqae_5.forward_decoder.gru.bias_ih_l0", "seq2seqae_5.forward_decoder.gru.bias_hh_l0", "seq2seqae_5.forward_decoder.gru.weight_ih_l0_reverse", "seq2seqae_5.forward_decoder.gru.weight_hh_l0_reverse", "seq2seqae_5.forward_decoder.gru.bias_ih_l0_reverse", "seq2seqae_5.forward_decoder.gru.bias_hh_l0_reverse". 
        Unexpected key(s) in state_dict: "epoch", "state_dict", "acc". 
```

Looking forward to your kind reply at your earliest convenience!

**Comment by absdnd** [comment]
I see thanks for pointing this out! What's the pytorch version you're using?
